### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Arthur-Milchior** [johnpincock/SpecialFields#15]
Hi,

Would you please accept to add a license to the project. For it to be compatible with anki it should be GPLv3 or AGPLv3. If you use AGPLv3 I won't be allowed to contribute anymore in a week, so I strongly suggest GPLv3. If you don't add a licence, I won't be allowed either. I give my permission for both. Of course, both @AnKingMed and @johnpincock you must both agree too.

**Comment by AnKingMed** [comment]
Definitely ok with it

**Comment by johnpincock** [comment]
Yeah sure thing, I'm happy to use the GPLv3 license, - to do that do i just copy the text from
GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007 etc...  and put it in a file called LICENSE ? Also out of general interest - what do you mean by "being allowed" ?

Thanks, JP

**Comment by Arthur-Milchior** [comment]
Yeah, copying the file is great. This way github will see the license automatically.

**Comment by Arthur-Milchior** [comment]
I'll be a software engineer starting the 6th of April. It seems that my employer has its word in anything which may be considered as related to my job, even on my free time. One rule to have automatically the authorization to contribute is that the free software has some specific license. AGPL is not an authorized license, so I'd need to ask for permission for each software I contribute to. GPL is authorized

**Comment by johnpincock** [comment]
Congrats with the new job ! - Interesting to know about the License.

**Comment by Arthur-Milchior** [comment]
If you're curious, you can see the detail on https://opensource.google/docs/using/agpl-policy/
