### ISSUE TITLE
Config window error on Anki 2.1.29beta1

### ISSUE THREAD

**Issue by amazeum** [johnpincock/SpecialFields#19]
It appears there was a change in how some windows are rendered in Anki 2.1.29beta1. This is the error message from trying to pull up Special Fields on Anki 2.1.29beta1 on macOS 15.15.6:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.29 (1b441f50) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-07-22 08:20:33
Add-ons possibly involved: ⁨Special Fields⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/amazeum/Library/Application Support/Anki2/addons21/1102281552/dialog.py", line 316, in onFields
    FieldDialog(mw, fields, parent=self)
  File "/Users/amazeum/Library/Application Support/Anki2/addons21/1102281552/dialog.py", line 41, in __init__
    self.form.buttonBox.button(
AttributeError: 'NoneType' object has no attribute 'setAutoDefault'

**Comment by ertwro** [comment]
Same error on windows 10. Anki version 2.1.28

**Comment by johnpincock** [comment]
Thanks for the heads up, I've just committed a potential fix

**Comment by amazeum** [comment]
@johnpincock It seems to be working great on 2.1.29 stable. Thank you for the quick turnaround! 🥇
