### ISSUE TITLE
[Suggestion] Add command to enable all fields as special fields

### ISSUE THREAD

**Issue by Krakyn** [johnpincock/SpecialFields#2]
Could you add a command so that instead of manually adding special fields to the config (e.g. u"Text"), all fields are enabled as a special field? This would make it really easy to import (combine) tags only without affecting the rest of the card. Thanks!

**Comment by AnKingMed** [comment]
I have just copied all my fields to the line below that has the # on it so its commented out. Then when I need to enable all fields, I can quickly copy and paste that whole line in

**Comment by AnKingMed** [comment]
This got added in to the latest version :)
