### ISSUE TITLE
2.1.45 Alpha 1 -> add-on broken

### ISSUE THREAD

**Issue by NamelessGO** [johnpincock/SpecialFields#28]
![image](https://user-images.githubusercontent.com/66227691/118549965-2f990900-b72a-11eb-818f-5b4a4e0a1032.png)
https://www.reddit.com/r/Anki/comments/neoihx/anki_2145_alpha/ (changelogs)

**Comment by sobjornstad** [comment]
I'm trying out my add-ons on 2.1.45, and it appears that `TemplateDict` should have a `Template` alias as well to match this. I'm probably just going to kick out new versions, but this might break someone else too.

**Comment by AnKingMed** [comment]
Should be working now
